# Generated by Django 5.1.15 on 2026-09-16 13:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpaFirm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CPA firm',
                'verbose_name_plural': 'CPA firms',
                'ordering': ['firm_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('capex_threshold', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.cpafirm')),
            ],
            options={
                'verbose_name': 'client account',
                'verbose_name_plural': 'client accounts',
                'ordering': ['client_name'],
                'constraints': [models.UniqueConstraint(fields=('firm', 'client_name'), name='uniq_client_name_per_firm')],
            },
        ),
    ]
