# Generated by Django 5.1.15 on 2026-09-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccount',
            name='capex_threshold',
        ),
    ]
