# Generated by Django 5.1.15 on 2026-09-16 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_clientaccount_capex_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('RAW', 'Raw'), ('EXTRACTED', 'Extracted'), ('NEEDS_REVIEW', 'Needs review'), ('PENDING_CLIENT', 'Pending client'), ('BLOCKED_COMPLIANCE', 'Blocked on compliance'), ('COMMITTED', 'Committed')], db_index=True, default='RAW', max_length=50)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(default='Portal Upload', max_length=100)),
                ('raw_input', models.TextField(blank=True)),
                ('sot_markdown', models.TextField(blank=True)),
                ('file_names', models.JSONField(blank=True, default=list)),
                ('reference_files', models.JSONField(blank=True, default=list)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('pending_plan', models.JSONField(blank=True, default=dict)),
                ('journal_entry', models.JSONField(blank=True, null=True)),
                ('blocker', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.clientaccount')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'state'], name='core_submis_client__a7fb24_idx')],
            },
        ),
    ]
