# Generated by Django 5.1.15 on 2026-09-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='blocker_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='chat_messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
