# Generated by Django 5.1.15 on 2026-09-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_submission_blocker_resolved_submission_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='document_context',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
