# Generated by Django 5.1.15 on 2026-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submission_document_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
