[theme]
primaryColor = "#1570EF"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#101828"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 8501
maxUploadSize = 100
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "auto"

[browser]
gatherUsageStats = false
